---
- name: config_conntrackd | configuring conntrackd
  template: src=etc/conntrackd/conntrackd.conf.j2 dest=/etc/conntrackd/conntrackd.conf owner=root group=root mode=0644 backup=yes

- name: copy primary-backup.sh
  command: cp /usr/share/doc/conntrackd/examples/sync/primary-backup.sh /etc/conntrackd/
